using System;
using System.Collections.Generic;
using System.Text;

namespace DnDPlayerSheet
{
	// Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
	public static class IconFont
	{
		public const string Account = "\U000f0004";
		public const string AccountCircle = "\U000f0009";
		public const string ScriptText = "\U000f0bc2";
		public const string Script = "\U000f0bc1";
		public const string ArmFlex = "\U000f0fd7";
		public const string Cog = "\U000f0493";
		public const string ShapePlus = "\U000f0495";
		public const string Toolbox = "\U000f09ac";
		public const string Wrench = "\U000f05b7";
		public const string ProgressWrench = "\U000f0cbd";
		public const string Pencil = "\U000f03eb";
		public const string Floppy = "\U000f0249";
		public const string Plus = "\U000f0415";
		public const string PlusBox = "\U000f0416";
		public const string Minus = "\U000f0374";
		public const string MinusBox = "\U000f0375";
		public const string TrashCan = "\U000f0a79";
		public const string TrashCanOutline = "\U000f0a7a";
	}
}