using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Android.Views;
using Android.Widget;

namespace DnDPlayerSheet.Droid.Resources
{
	// Generated by IconFont2Code: https://andreinitescu.github.io/IconFont2Code
	static class IconFont
	{
		public const string Account = "\U000f0004";
		public const string AccountCircle = "\U000f0009";
		public const string ScriptText = "\U000f0bc2";
		public const string Script = "\U000f0bc1";
		public const string ArmFlex = "\U000f0fd7";
		public const string Cog = "\U000f0493";
		public const string ShapePlus = "\U000f0495";
		public const string Toolbox = "\U000f09ac";
		public const string Wrench = "\U000f05b7";
		public const string ProgressWrench = "\U000f0cbd";
	}
}